# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'taksitcikar.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector as mysql

class cikar(object):
    def setupUi2(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 97)
        Form.setStyleSheet("QPushButton {\n"
"  background-color: #0d6efd;\n"
"  color: #fff;\n"
"  font-weight: 600;\n"
"  border-radius: 8px;\n"
"  border: 1px solid #0d6efd;\n"
"  padding: 5px 15px;\n"
"  margin-top: 10px;\n"
"  outline: 0px;\n"
"}\n"
"QPushButton:hover,\n"
"QPushButton:focus {\n"
"  background-color: #0b5ed7;\n"
"  border: 3px solid #9ac3fe;\n"
"}\n"
"QLineEdit {\n"
"  border-radius: 8px;\n"
"  border: 1px solid #e0e4e7;\n"
" \n"
"}\n"
"QLineEdit:focus {\n"
"  border: 1px solid #d0e3ff;\n"
"}\n"
"\n"
"QLineEdit::placeholder {\n"
"  color: #767e89;\n"
"}\n"
"")
        self.mydb=mysql.connect(
            host="localhost",
            user="root",
            password="admin123",
            database="kullanici")
        self.mycursor=self.mydb.cursor()
        self.ID = QtWidgets.QLineEdit(Form)
        self.ID.setGeometry(QtCore.QRect(0, 20, 91, 20))
        self.ID.setObjectName("ID")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(40, 0, 51, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(140, 0, 47, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(250, 0, 81, 21))
        self.label_3.setObjectName("label_3")
        self.taksit = QtWidgets.QLineEdit(Form)
        self.taksit.setGeometry(QtCore.QRect(110, 20, 91, 20))
        self.taksit.setObjectName("taksit")
        self.tarih = QtWidgets.QLineEdit(Form)
        self.tarih.setGeometry(QtCore.QRect(230, 20, 91, 20))
        self.tarih.setObjectName("tarih")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(10, 40, 301, 41))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        self.pushButton.clicked.connect(self.taksitode)
        
    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "ID"))
        self.label_2.setText(_translate("Form", "TAKSİT"))
        self.label_3.setText(_translate("Form", "SON TARİH"))
        
        self.pushButton.setText(_translate("Form", "PushButton"))
    def taksitode(self):
        print("pressed")
        command="SELECT taksit From taksit WHERE ID=(%s)"
        value=[self.ID.text()]
        self.mycursor.execute(command,value)
        results=self.mycursor.fetchall()
        taksit=(int(results[0][0]))
        existingtaksit=int(float((self.taksit.text())))
        if (taksit-existingtaksit)<=0:
            command="DELETE FROM taksit WHERE ID=(%s)"
            value=[self.ID.text()]
            self.mycursor.execute(command,value)
            self.mydb.commit()
        else:
            command="Update taksit SET taksit=(%s), tarih=STR_TO_DATE(%s,'%Y-%m-%d') Where Id=(%s)"
            value=((taksit-existingtaksit),self.tarih.text(),int(self.ID.text()))
            self.mycursor.execute(command,value)
            self.mydb.commit()

if __name__ == "__main__":
            import sys
            app = QtWidgets.QApplication(sys.argv)
            MainWindow = QtWidgets.QMainWindow()
            ui =cikar()
            ui.setupUi2(MainWindow)
            MainWindow.show()
            sys.exit(app.exec_())